name = "UserConfig"
uuid = "38191a5c-9707-409e-a5e4-8d538fd01011"
authors = ["Oliver Woodford"]
version = "1.0.1"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
JLD2 = "0.4"
julia = "1.6"
Test = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
